

name: TruffleHog
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 10
    - name: Secret Scanning
      uses: trufflesecurity/trufflehog@main
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: scan-push
      uses: trufflesecurity/trufflehog@main
      with:
        base: ""
        head: ${{ github.ref_name }}
        extra_args: --debug --only-verified
